// Firebase Web App configuration. NOT secret — the Web API key and IDs are
// public by design (security is enforced by Firestore Rules + App Check,
// not by hiding these). This file is GENERATED by scripts/bootstrap-gcp.sh
// when you stand up a new environment; edit there, or re-run the bootstrap.
export const firebaseConfig = {
  projectId: 'vacaciones-dev-b3158',
  appId: '1:1000746698778:web:0f498b2ad533327a9b69a3',
  storageBucket: 'vacaciones-dev-b3158.firebasestorage.app',
  apiKey: 'AIzaSyDdJsNemH83qjri-EOUURBPD4sQA2qkayg',
  authDomain: 'vacaciones-dev-b3158.firebaseapp.com',
  messagingSenderId: '1000746698778',
};
