export const ECONOMY = {
  ONBOARDING_GRANT: 20,
  MONTHLY_STIPEND: 10,
  COVERAGE_PRICE_PER_DAY: 5,
  COVERAGE_PRICE_HALF_DAY: 2,
  WEEKEND_MULTIPLIER: 2,
  HOLIDAY_MULTIPLIER: 2,
  TRANSACTION_FEE: 1,
  LEADERBOARD_WINDOW_DAYS: 90,
  MAX_GIFT_PER_WEEK: 5,
  MAX_MANAGER_ADVANCE_PER_QUARTER: 10,
} as const;
